### ISSUE TITLE
Ability to bypass retain messages?

### ISSUE THREAD

**Issue by ilyaroot** [oswjk/mqtt#9]
Would be very useful to have an option not to show retain messages on broker at first connect.
Like mosquitto_sub -R. "If this argument is given, messages that are received that have the retain bit set will not be printed."

**Comment by oskaritimperi** [comment]
Do you mean in the `sub.c` tool?

**Comment by ilyaroot** [comment]
Sorry, found the way mosquitto done:
if(message->retain && cfg->no_retain) return;

struct MqttMessage has int retain flag, so I can just not process these messages at onMessage callback procedure.

Thank you very much for mqqt client, coded in a single file! Very useful at embedded systems.

**Comment by oskaritimperi** [comment]
Nice to hear you found out a solution. And very nice to hear that this implementation can be used in embedded environment. :-)
